interface Course {
	id: string;
	title: string;
	image: string;
	category: string;
	href: string;
}

// Пример данных (можно заменить на props)
export const courses: Course[] = [
	{
		id: '1',
		title: 'Java Junior Веб Разработчик',
		image: '/courses/programming/javajunior.svg',
		category: 'Программирование',
		href: '/courses/programming/java-junior',
	},
	{
		id: '2',
		title: 'Java Разработчик с 0 до PRO',
		image: '/courses/programming/javapro.svg',
		category: 'Программирование',
		href: '/courses/programming/java-pro',
	},
	{
		id: '3',
		title: 'C++ Разработчик',
		image: '/courses/programming/cplus.svg',
		category: 'Программирование',
		href: '/courses/programming/c-plus-plus',
	},
	{
		id: '4',
		title: 'Python Аналитик Данных',
		image: '/courses/programming/python.svg',
		category: 'Программирование',
		href: '/courses/programming/python-data-science',
	},
	{
		id: '5',
		title: 'Python (Django) Веб-Разработчик',
		image: '/courses/programming/django.svg',
		category: 'Программирование',
		href: '/courses/programming/python-web-development',
	},
	{
		id: '6',
		title: 'Java Middle Разработчик',
		image: '/courses/programming/javamiddle.svg',
		category: 'Программирование',
		href: '/courses/programming/java-middle-spring-hibernate',
	},
	{
		id: '7',
		title: 'PHP Junior Программист',
		image: '/courses/programming/php.svg',
		category: 'Программирование',
		href: '/courses/programming/php-junior',
	},
	{
		id: '8',
		title: 'Тестирование ПО (QA)',
		image: '/courses/testing/testing.svg',
		category: 'Тестирование',
		href: '/courses/testing/testing-qa',
	},
	{
		id: '9',
		title: 'QA Тестирование (Java)',
		image: '/courses/testing/java.svg',
		category: 'Тестирование',
		href: '/courses/testing/qa-avtomation',
	},
	{
		id: '10',
		title: 'QA Тестирование (Python)',
		image: '/courses/testing/python.svg',
		category: 'Тестирование',
		href: '/courses/testing/python-qa-avtomation',
	},
	{
		id: '11',
		title: 'Тестирование ПО (PRO Версия)',
		image: '/courses/testing/pro.svg',
		category: 'Тестирование',
		href: '/courses/testing/qa-pro',
	},
	{
		id: '12',
		title: 'Javascript (Full-stack)',
		image: '/courses/web/full.svg',
		category: 'Веб Разработка',
		href: '/courses/web-development/java-script-full-stack',
	},
	{
		id: '13',
		title: 'Javascript (Front-end)',
		image: '/courses/web/front.svg',
		category: 'Веб Разработка',
		href: '/courses/web-development/javascript-front-end',
	},
	{
		id: '14',
		title: 'HTML&CSS Верстка сайтов',
		image: '/courses/web/html.svg',
		category: 'Веб Разработка',
		href: '/courses/web-development/html-css-moskow',
	},
	{
		id: '15',
		title: 'Javascript (без верстки)',
		image: '/courses/web/javascript.svg',
		category: 'Веб Разработка',
		href: '/courses/web-development/java-script-language',
	},
	{
		id: '16',
		title: 'UI&UI Веб Дизайн',
		image: '/courses/design/ux.svg',
		category: 'Дизайн',
		href: '/courses/design/web-design-ui-ux',
	},
	{
		id: '17',
		title: 'Графический дизайн',
		image: '/courses/design/graph.svg',
		category: 'Дизайн',
		href: '/courses/design/graphic-designer',
	},
	{
		id: '18',
		title: 'Дизайн для начинающих',
		image: '/courses/design/junior.svg',
		category: 'Дизайн',
		href: '/courses/design/design-dlya-nachinayshih',
	},
	{
		id: '19',
		title: 'SMM Продвижение в соц сетях',
		image: '/courses/marketing/smm.svg',
		category: 'Маркетинг',
		href: '/courses/marketing/smm',
	},
	{
		id: '20',
		title: 'Интернет-маркетинг',
		image: '/courses/marketing/internet.svg',
		category: 'Маркетинг',
		href: '/courses/marketing/internet-marketing',
	},
	{
		id: '21',
		title: 'Контекстная реклама',
		image: '/courses/marketing/yandex.svg',
		category: 'Маркетинг',
		href: '/courses/marketing/reklama-ppc',
	},
	{
		id: '22',
		title: 'Таргетированная реклама',
		image: '/courses/marketing/target.svg',
		category: 'Маркетинг',
		href: '/courses/marketing/reklama-vkontakte-telegram',
	},
	{
		id: '23',
		title: 'Android-Разработчик (Java&Kotlin)',
		image: '/courses/mobile/android.svg',
		category: 'Моб. разработка',
		href: '/courses/mobile-development/java-android',
	},
	{
		id: '24',
		title: 'IOS Разработчик',
		image: '/courses/mobile/ios.svg',
		category: 'Моб. разработка',
		href: '/courses/mobile-development/mobiledev-ios',
	},
	{
		id: '25',
		title: '3Ds Max',
		image: '/courses/threeD/3d.svg',
		category: '3D моделирование',
		href: '/courses/3d-modeling/3d-max',
	},
	{
		id: '26',
		title: 'IT Project менеджер',
		image: '/courses/other/itproject.svg',
		category: 'Другие курсы',
		href: '/courses/other/pm-kurs',
	},
	{
		id: '27',
		title: 'Менеджер маркетплейсов',
		image: '/courses/other/marketplace.svg',
		category: 'Другие курсы',
		href: '/courses/other/manager-marketplace',
	},
];
