import type { Metadata } from 'next';
import { Golos_Text } from 'next/font/google';
import './globals.css';

const GolosText = Golos_Text({
	variable: '--golos-text',
	subsets: ['latin'],
	weight: ['400', '500', '700', '900'],
	fallback: ['Arial', 'Helvetica', 'sans-serif'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={GolosText.variable}>{children}</body>
		</html>
	);
}
